name: Upload release files

on:
  release:
    types: [created]

jobs:
  release:
    name: Upload release files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload release files
        uses: actions/upload-artifact@v2
        with:
          name: release-files
          path: ${{ github.event.release.assets[0].name }}

      - name: Move release files
        run: mv ${{ github.workspace }}/${{ github.event.release.assets[0].name }} .
